CREATE TABLE IF NOT EXISTS addresses
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    apartment_number character varying(10) COLLATE pg_catalog."default",
    city character varying(255) COLLATE pg_catalog."default",
    house_number character varying(10) COLLATE pg_catalog."default" NOT NULL,
    street character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT addresses_pkey PRIMARY KEY (id)
    )

GO