CREATE TABLE IF NOT EXISTS orders
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_date timestamp(6) without time zone,
    status character varying(20) COLLATE pg_catalog."default",
    user_id integer,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
    )

GO

ALTER TABLE IF EXISTS orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id)
    REFERENCES users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION

GO