ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS fke8vydtk7hf0y16bfm558sywbb

GO

ALTER TABLE IF EXISTS users DROP CONSTRAINT IF EXISTS fkp56c1712k691lhsyewcssf40f

GO

drop table if exists users

GO